spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost/PSIDP
    username: SYSDBA
    password: SYSDBA
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.kd.servicedemo.mapper: debug
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true