CREATE SCHEMA "MYBATIS" AT "PSIDP" AUTHORIZATION "SYSDBA";


CREATE TABLE "PSIDP"."MYBATIS"."DATABASE"(
"ID" VARCHAR(50),
"NAME" VARCHAR(50),
"DRIVERNAME" VARCHAR(50),
"URL" VARCHAR(50),
"USERNAME" VARCHAR(50),
"PASSWORD" VARCHAR(50),
PRIMARY KEY("ID"))
 STORAGE( INITIAL 1 , NEXT 1 , MINEXTENTS 1 , on "PRIMARY", FILLFACTOR 0 ) ;